import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/shared/Navbar";
import { colors } from "@/src/lib/colors";
import Footer from "@/src/shared/Footer";
import Cta from "@/src/components/home/Cta";
import ProductWrapper from "@/src/providers/ProductWrapper";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "KICKS",
  description: "Generated by KICKS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className}  antialiased`}
        style={{ backgroundColor: colors.background }}
      >
        <ProductWrapper>
          <Navbar />
          {children}
          <Cta />
          <Footer />
        </ProductWrapper>
      </body>
    </html>
  );
}
